version: "3.3"
services:
  xui:
    image: 'alireza7/x-ui:latest'
    container_name: 'x-ui-cnt'
    network_mode: host
    environment:
      - XRAY_VMESS_AEAD_FORCED=false
    volumes:
      - ./db:/etc/x-ui/
      - ../certbot/certbot/conf:/root/cert/
    restart: unless-stopped
