version: "3.7"

services:
  pingtunnelclient:
    image: ghcr.io/rahbazkon/pingtunnel:v1.0.0
    container_name: icmp-client
    restart: always
    networks:
      - net
    command: "./pingtunnel -type client -l 0.0.0.0:1080 -s ${SERVER} -t ${SERVER}:{SERVER_PORT} -tcp 1 -key ${KEY}"


  pingtunnelclientnginx:
    image: nginx:1.23.2
    container_name: "icmp-client-nginx"
    networks:
      - net
    ports:
      - '443:443'
      - '80:80'
    restart: unless-stopped
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ../certbot/certbot/conf:/etc/letsencrypt
      - ../certbot/certbot/www:/var/www/certbot
    depends_on:
      - pingtunnelclient


networks:
  net:
    name: 'net'
