version: "3.3"
services:
  hans:
    image: petrich/hans
    container_name: hans-client
    command: ["hans.sh", "-u", "nobody", "-d", "hans", "-v", "-f", "-c", PTUNNEL_SERVER_IP, "-p", PTUNNEL_PASS, "-qi", "-m", "1450"]
    platform: linux/amd64
    restart: always
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true

  nginx:
    image: nginx:1.23.2
    container_name: "hans-client-nginx"
    networks:
      - net
    ports:
      - '443:443'
      - '80:80'
    restart: unless-stopped
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ../../certbot/certbot/conf:/etc/letsencrypt
      - ../../certbot/certbot/www:/var/www/certbot
    depends_on:
      - hans
  
networks:
  net:
    name: 'net'
