version: "3.3"
services:
  x-ui:
    image: ghcr.io/rahbazkon/x-ui:latest
    container_name: 'x-ui-nginx-x-ui-cnt'
    networks:
      - net
    ports:
      - "54321:54321"
    volumes:
      - ./db:/etc/x-ui/
      - ../certbot/certbot/conf:/root/cert/
    restart: unless-stopped


  nginx:
    image: nginx:1.23.2
    container_name: "certbot-nginx-nginx-cnt"
    networks:
      - net
    ports:
      - '443:443'
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../certbot/certbot/conf:/etc/letsencrypt
      - ../certbot/certbot/www:/var/www/certbot
    depends_on:
      - x-ui
